apiVersion: v1
kind: Service
metadata:
  name: spring-websocket-demo-service
spec:
  type: NodePort
  selector:
    app: spring-websocket-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080