logging:
  level:
    org.springframework.messaging: trace

---
spring:
  profiles: production

logging:
  level:
    org.springframework.messaging: info

stomp:
  relay-host: ${STOMP_RELAY_HOST}
  relay-post: ${STOMP_RELAY_PORT}
  system-login: ${STOMP_SYSTEM_LOGIN}
  system-passcode: ${STOMP_SYSTEM_PASSCODE}